apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: print-tag
  labels:
    app: print-tag
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: print-tag
  strategy:
    blueGreen:
      activeService: svc-prod
      previewService: svc-test
      autoPromotionEnabled: false
  template:
    metadata:
      labels:
        app: print-tag
    spec:
      containers:
        - name: print-tag
          image: "kanatakita/print-tag:v1"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
