---
apiVersion: v1
kind: Service
metadata:
  name: svc-prod
  labels:
    app: print-tag
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31001
      protocol: TCP
      name: http
  selector:
    app: print-tag
---
apiVersion: v1
kind: Service
metadata:
  name: svc-test
  labels:
    app: print-tag
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31002
      protocol: TCP
      name: http
  selector:
    app: print-tag

